package basicdata

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	LessonRouter
	ChapterRouter
	ResourceRouter
	CollegeRouter
	ProfessionalRouter
	ClassRouter
	TermRouter
	TeachClassStudentRouter
	TeachClassRouter
	StudentRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
