package basicdata

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	LessonRouter
	ChapterRouter
	KnowledgeRouter
	ResourceRouter
	ResandknowRouter
	CollegeRouter
	ProfessionalRouter
	ClassRouter
	StudentRouter
	TermRouter
	TeachClassStudentRouter
	TeachClassRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
