package {{ .PackageName }}

type ApiGroup struct {
	// Code generated by github.com/prl26/exam-system/server Begin; DO NOT EDIT.

	// Code generated by github.com/prl26/exam-system/server End; DO NOT EDIT.
}
