package examManage

type ApiGroup struct {
	// Code generated by github.com/prl26/exam-system/server Begin; DO NOT EDIT.

	PaperTemplateApi
	PaperTemplateItemApi
	PaperQuestionMergeApi
	ExamPaperApi

	ExamStudentPaperApi
	// Code generated by github.com/prl26/exam-system/server End; DO NOT EDIT.
}
