package questionBank

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	QuestionBankMultipleChoiceApi
	QuestionBankJudgeApi
	QuestionBankSupplyBlankApi
	QuestionBankOptionsApi
	ProgramApi
	QuestionBankApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
