package questionBank

type ApiGroup struct {
	// Code generated by github.com/prl26/exam-system/server Begin; DO NOT EDIT.

	QuestionBankMultipleChoiceApi
	QuestionBankJudgeApi
	QuestionBankSupplyBlankApi
	QuestionBankOptionsApi
	QuestionBankProgrammApi
	QuestionBankProgrammCaseApi
	ProgrammLanguageMergeApi
	// Code generated by github.com/prl26/exam-system/server End; DO NOT EDIT.
}
