package questionBank

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	QuestionBankKnowledgeMergeApi
	QuestionBankMultipleChoiceApi
	QuestionBankJudgeApi
	QuestionBankSupplyBlankApi
	QuestionBankOptionsApi
	QuestionBankProgrammApi
	QuestionBankProgrammCaseApi
	ProgrammLanguageMergeApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
