package lesson

type ServiceGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.

	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
