package examManage

type RouterGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.

	PaperTemplateRouter
	PaperTemplateItemRouter
	PaperQuestionMergeRouter
	ExamPaperRouter
	ExamStudentPaperRouter
	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
