package lessondata

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	VideoResourcesService
	ArticleResourcesService
	ResourcePracticeService
	ResourcesTestService
	KnowledgeService

	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
