package lessondata

type ApiGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.

	VideoResourcesApi
	ArticleResourcesApi
	ResourcePracticeApi
	ResourcesTestApi
	KnowledgeApi

	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
