package teachplan

type RouterGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.

	TeachAttendanceRouter
	TeachAttendanceRecordRouter
	ScoreRouter
	ExamPlanRouter
	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
