package lessondata

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	VideoResourcesRouter
	ArticleResourcesRouter
	ResourcePracticeRouter
	ResourcesTestRouter
	KnowledgeRouter

	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
