package examManage

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	PaperTemplateRouter
	PaperTemplateItemRouter
	PaperQuestionMergeRouter
	ExamPaperRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
