package lessondata

import "github.com/flipped-aurora/gin-vue-admin/server/api/v1/lessondata"

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	lessondata.KnowledgeApi
	lessondata.QuestionBankKnowledgeMergeApi
	lessondata.QuestionBankMultipleChoiceApi
	lessondata.QuestionBankJudgeApi
	lessondata.QuestionBankSupplyBlankApi
	lessondata.QuestionBankOptionsApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
