package basicdata

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	LessonService
	ChapterService
	ResourceService
	CollegeService
	ProfessionalService
	ClassService
	StudentService
	TermService
	TeachClassStudentService
	TeachClassService
	LearnResourcesChapterMergeService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
