package basicdata

type ServiceGroup struct {
	// Code generated by github.com/prl26/exam-system/server Begin; DO NOT EDIT.

	LessonService
	ChapterService
	ResourceService
	CollegeService
	ProfessionalService
	ClassService
	TermService
	TeachClassService
	LearnResourcesChapterMergeService
	StudentService
	MultiTableService
	// Code generated by github.com/prl26/exam-system/server End; DO NOT EDIT.
}
