package teachplan

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	TeachAttendanceRouter
	TeachAttendanceRecordRouter
	ScoreRouter
	ExamPlanRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
