package examManage


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	PaperTemplateService
	PaperTemplateItemService
	PaperQuestionMergeService
	ExamPaperService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

