package examManage

type ServiceGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.

	PaperTemplateService
	PaperTemplateItemService
	PaperQuestionMergeService
	ExamPaperService
	ExamStudentPaperService
	ExamStatusService
	ExamService
	TargetExamPaperService
	DraftPaperService
	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
