package examManage

type ServiceGroup struct {
	// Code generated by github.com/prl26/exam-system/server Begin; DO NOT EDIT.

	PaperTemplateService
	PaperTemplateItemService
	PaperQuestionMergeService
	ExamPaperService
	ExamStudentPaperService
	// Code generated by github.com/prl26/exam-system/server End; DO NOT EDIT.
}
