package teachplan

type ApiGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.

	TeachAttendanceApi
	TeachAttendanceRecordApi
	ScoreApi
	ExamPlanApi
	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
