package questionBank

/**

 * @Author: AloneAtWar

 * @Date:   2022/8/24 15:12

 * @Note:

 **/
type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/questionBankService Begin; DO NOT EDIT.
	MultipleChoiceService
	JudgeService
	SupplyBlankService
	OptionsService
	ProgrammService
	QuestionBankService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/questionBankService End; DO NOT EDIT.
}
