package basicdata

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	LessonApi
	ChapterApi
	ResourceApi
	CollegeApi
	ProfessionalApi
	ClassApi
	TermApi
	TeachClassStudentApi
	TeachClassApi
	LearnResourcesChapterMergeApi
	StudentApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
