package basicdata

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	LessonApi
	ChapterApi
	KnowledgeApi
	ResourceApi
	ResandknowApi
	CollegeApi
	ProfessionalApi
	ClassApi
	StudentApi
	TermApi
	TeachClassStudentApi
	TeachClassApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
