package teachplan

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	TeachAttendanceApi
	TeachAttendanceRecordApi
	ScoreApi
	ExamPlanApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
