package basicdata

type ApiGroup struct {
	// Code generated by github.com/prl26/exam-system/server Begin; DO NOT EDIT.

	LessonApi
	ChapterApi
	ResourceApi
	CollegeApi
	ProfessionalApi
	ClassApi
	TermApi
	TeachClassApi
	LearnResourcesChapterMergeApi
	StudentApi
	MultiTableApi
	// Code generated by github.com/prl26/exam-system/server End; DO NOT EDIT.
}
