package examManage

import (
	"github.com/prl26/exam-system/server/api/frontDesk/examManage"
)

type ApiGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.

	PaperTemplateApi
	PaperTemplateItemApi
	PaperQuestionMergeApi
	ExamPaperApi
	ExamStudentPaperApi
	ExamGroup examManage.ApiGroup
	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
