package examManage

type ApiGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.
	PaperTemplateApi
	PaperTemplateItemApi
	PaperQuestionMergeApi
	ExamPaperApi
	ExamStudentPaperApi
	DraftPaperApi
	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
