package examManage

import "github.com/prl26/exam-system/server/api/Backstage/examManage/frontEnd"

type ApiGroup struct {
	// Code generated by github.com/prl26/exam-system/server Begin; DO NOT EDIT.

	PaperTemplateApi
	PaperTemplateItemApi
	PaperQuestionMergeApi
	ExamPaperApi
	ExamStudentPaperApi
	ExamGroup frontEnd.ApiGroup
	// Code generated by github.com/prl26/exam-system/server End; DO NOT EDIT.
}
