package basicdata

type RouterGroup struct {
	// Code generated by github.com/prl26/frontExam-system/server Begin; DO NOT EDIT.

	LessonRouter
	ChapterRouter
	ResourceRouter
	CollegeRouter
	ProfessionalRouter
	ClassRouter
	TermRouter
	TeachClassStudentRouter
	TeachClassRouter
	StudentRouter
	// Code generated by github.com/prl26/frontExam-system/server End; DO NOT EDIT.
}
